/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        String[] args = {"input", "output", "transform"};
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(args), "app should have a greeting");
    }
}
