/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public String getGreeting(String[] strings) {
        StringBuilder sb = new StringBuilder();

        sb.append("Inputs received:");

        for (String str : strings) {
            sb.append(" \"").append(str).append("\"");
        }

        sb.append(".");

        return sb.toString();
    }

    public static void main(String[] args) {
        if (args.length < 3) {
            System.out.println("3 inputs required: \"input-file-path output-file-path transform-name\"");
            return;
        }

        System.out.println(new App().getGreeting(args));
    }
}
