/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.InvalidPathException;

public class App {
    public String getGreeting(String[] strings) {
        StringBuilder sb = new StringBuilder();
        sb.append("Inputs received:");

        for (String str : strings) {
            sb.append(" \"").append(str).append("\"");
        }

        sb.append(".");

        return sb.toString();
    }

    public static void main(String[] args) {
        if (args.length != 3) {
            System.out.println("Received " + args.length + " args.");
            System.out.println("3 inputs required: \"input-file-path output-file-path transform-name\".");
            System.out.println("*** Available transforms: \"bars\" ***");
            System.out.println("Future transforms: \"rotate\" 90-deg clockwise; \"mirror\" flip on horizontal.");
            return;
        }

        System.out.println(new App().getGreeting(args));

        String inFilePath = args[0];
        String outFilePath = args[1];
        String transformCmd = args[2];

        Bitmap bitmap = new Bitmap(inFilePath, outFilePath, transformCmd);

        try {
            bitmap.getInputFile();
            System.out.println("Read file " + bitmap.getInFilePath() + " successfully.");
        } catch (NullPointerException nullPointer) {
            System.out.println("Unable to read file at " + bitmap.getInFilePath());
            return;
        } catch (IOException inputOutput) {
            System.out.println("A problem occurred while reading " + bitmap.getInFilePath());
            return;
        }

        try {
            bitmap.processFile();
            System.out.println("Successfully applied transformation!");
        } catch (IllegalStateException illegalState) {
            System.out.println(illegalState.getMessage());
            return;
        }

        try {
            bitmap.createOutputFile();
            System.out.println("Wrote changes to file " + bitmap.getOutFilePath());
        } catch (InvalidPathException invalidPath) {
            System.out.println("Unable to create file at " + bitmap.getOutFilePath());
        } catch (FileNotFoundException fileNotFound) {
            System.out.println("Unable to find file at " + bitmap.getOutFilePath());
        } catch (IOException inputOutput) {
            System.out.println("Unable to write to file " + bitmap.getOutFilePath());
        }
    }
}
